import 'package:flutter/material.dart';

class AppColors {
  static const Color baseColorLight = Color(0xffFDFFFC);

  static ColorScheme lightScheme = ColorScheme.fromSwatch().copyWith(
    brightness: Brightness.light,
    primary: const Color(0xFF006E2C),
    onPrimary: const Color(0xFFFFFFFF),
    primaryContainer: const Color(0xFF8CFA9C),
    onPrimaryContainer: const Color(0xFF002108),
    secondary: const Color(0xFF516351),
    onSecondary: const Color(0xFFFFFFFF),
    secondaryContainer: const Color(0xFFD4E8D1),
    onSecondaryContainer: const Color(0xFF0F1F11),
    tertiary: const Color(0xFF39656C),
    onTertiary: const Color(0xFFFFFFFF),
    tertiaryContainer: const Color(0xFFBDEAF3),
    onTertiaryContainer: const Color(0xFF001F24),
    error: const Color(0xFFBA1A1A),
    errorContainer: const Color(0xFFFFDAD6),
    onError: const Color(0xFFFFFFFF),
    onErrorContainer: const Color(0xFF410002),
    background: const Color(0xFFFCFDF7),
    onBackground: const Color(0xFF1A1C19),
    surface: const Color(0xFFFCFDF7),
    onSurface: const Color(0xFF1A1C19),
    surfaceVariant: const Color(0xFFDDE5D9),
    onSurfaceVariant: const Color(0xFF424940),
    outline: const Color(0xFF727970),
    onInverseSurface: const Color(0xFFF0F1EB),
    inverseSurface: const Color(0xFF2E312D),
    inversePrimary: const Color(0xFF70DD82),
    shadow: const Color(0xFF000000),
    surfaceTint: const Color(0xFF006E2C),
    outlineVariant: const Color(0xFFC1C9BE),
    scrim: const Color(0xFF000000),
  );

  static ColorScheme darkScheme = ColorScheme.fromSwatch().copyWith(
    brightness: Brightness.dark,
    primary: const Color(0xFF70DD82),
    onPrimary: const Color(0xFF003913),
    primaryContainer: const Color(0xFF00531F),
    onPrimaryContainer: const Color(0xFF8CFA9C),
    secondary: const Color(0xFFB8CCB5),
    onSecondary: const Color(0xFF243425),
    secondaryContainer: const Color(0xFF3A4B3A),
    onSecondaryContainer: const Color(0xFFD4E8D1),
    tertiary: const Color(0xFFA1CED6),
    onTertiary: const Color(0xFF00363D),
    tertiaryContainer: const Color(0xFF1F4D54),
    onTertiaryContainer: const Color(0xFFBDEAF3),
    error: const Color(0xFFFFB4AB),
    errorContainer: const Color(0xFF93000A),
    onError: const Color(0xFF690005),
    onErrorContainer: const Color(0xFFFFDAD6),
    background: const Color(0xFF1A1C19),
    onBackground: const Color(0xFFE2E3DD),
    surface: const Color(0xFF1A1C19),
    onSurface: const Color(0xFFE2E3DD),
    surfaceVariant: const Color(0xFF424940),
    onSurfaceVariant: const Color(0xFFC1C9BE),
    outline: const Color(0xFF8B9389),
    onInverseSurface: const Color(0xFF1A1C19),
    inverseSurface: const Color(0xFFE2E3DD),
    inversePrimary: const Color(0xFF006E2C),
    shadow: const Color(0xFF000000),
    surfaceTint: const Color(0xFF70DD82),
    outlineVariant: const Color(0xFF424940),
    scrim: const Color(0xFF000000)
  );
}